//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html class=&quot; responsive&quot; lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///			&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1&quot;&gt;
        ///		&lt;meta name=&quot;theme-color&quot; content=&quot;#171a21&quot;&gt;
        ///		&lt;title&gt;Destiny 2 on Steam&lt;/title&gt;
        ///	&lt;link rel=&quot;shortcut icon&quot; href=&quot;/favicon.ico&quot; type=&quot;image/x-icon&quot;&gt;
        ///
        ///	
        ///	
        ///	&lt;link href=&quot;https://store.akamai.steamstatic.com/public/shared/css/motiva_sans.css?v=Rc2hpzg2Ex3T&amp;amp;l=english&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Destiny_2 {
            get {
                return ResourceManager.GetString("Destiny-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html class=&quot; responsive&quot; lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///			&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1&quot;&gt;
        ///		&lt;meta name=&quot;theme-color&quot; content=&quot;#171a21&quot;&gt;
        ///		&lt;title&gt;Pre-purchase ELDEN RING on Steam&lt;/title&gt;
        ///	&lt;link rel=&quot;shortcut icon&quot; href=&quot;/favicon.ico&quot; type=&quot;image/x-icon&quot;&gt;
        ///
        ///	
        ///	
        ///	&lt;link href=&quot;https://store.akamai.steamstatic.com/public/shared/css/motiva_sans.css?v=Rc2hpzg2Ex3T&amp;amp;l=english&quot; rel=&quot;stylesheet&quot; t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Elden_Ring {
            get {
                return ResourceManager.GetString("Elden-Ring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html class=&quot; responsive&quot; lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///			&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1&quot;&gt;
        ///		&lt;meta name=&quot;theme-color&quot; content=&quot;#171a21&quot;&gt;
        ///		&lt;title&gt;Save 50% on Hollow Knight on Steam&lt;/title&gt;
        ///	&lt;link rel=&quot;shortcut icon&quot; href=&quot;/favicon.ico&quot; type=&quot;image/x-icon&quot;&gt;
        ///
        ///	
        ///	
        ///	&lt;link href=&quot;https://store.akamai.steamstatic.com/public/shared/css/motiva_sans.css?v=Rc2hpzg2Ex3T&amp;amp;l=english&quot; rel=&quot;stylesheet&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Hollow_Knight {
            get {
                return ResourceManager.GetString("Hollow-Knight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html class=&quot; responsive&quot; lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///			&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1&quot;&gt;
        ///		&lt;meta name=&quot;theme-color&quot; content=&quot;#171a21&quot;&gt;
        ///		&lt;title&gt;Kingdomfall on Steam&lt;/title&gt;
        ///	&lt;link rel=&quot;shortcut icon&quot; href=&quot;/favicon.ico&quot; type=&quot;image/x-icon&quot;&gt;
        ///
        ///	
        ///	
        ///	&lt;link href=&quot;https://store.akamai.steamstatic.com/public/shared/css/motiva_sans.css?v=Rc2hpzg2Ex3T&amp;amp;l=english&quot; rel=&quot;stylesheet&quot; type=&quot;text/cs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Kingdomfall {
            get {
                return ResourceManager.GetString("Kingdomfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html class=&quot; responsive&quot; lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///			&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1&quot;&gt;
        ///		&lt;meta name=&quot;theme-color&quot; content=&quot;#171a21&quot;&gt;
        ///		&lt;title&gt;Many Buttons to Press on Steam&lt;/title&gt;
        ///	&lt;link rel=&quot;shortcut icon&quot; href=&quot;/favicon.ico&quot; type=&quot;image/x-icon&quot;&gt;
        ///
        ///	
        ///	
        ///	&lt;link href=&quot;https://store.akamai.steamstatic.com/public/shared/css/motiva_sans.css?v=Rc2hpzg2Ex3T&amp;amp;l=english&quot; rel=&quot;stylesheet&quot; typ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Many_Buttons_to_Press {
            get {
                return ResourceManager.GetString("Many-Buttons-to-Press", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html class=&quot; responsive&quot; lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///			&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1&quot;&gt;
        ///		&lt;meta name=&quot;theme-color&quot; content=&quot;#171a21&quot;&gt;
        ///		&lt;title&gt; on Steam&lt;/title&gt;
        ///	&lt;link rel=&quot;shortcut icon&quot; href=&quot;/favicon.ico&quot; type=&quot;image/x-icon&quot;&gt;
        ///
        ///	
        ///	
        ///	&lt;link href=&quot;https://store.cloudflare.steamstatic.com/public/shared/css/motiva_sans.css?v=2C1Oh9QFVTyK&amp;amp;l=english&amp;amp;_cdn=cloudflare&quot; rel=&quot;stylesheet&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Space_Rift {
            get {
                return ResourceManager.GetString("Space-Rift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html class=&quot; responsive&quot; lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///			&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1&quot;&gt;
        ///		&lt;meta name=&quot;theme-color&quot; content=&quot;#171a21&quot;&gt;
        ///		&lt;title&gt;Texture Assembler on Steam&lt;/title&gt;
        ///	&lt;link rel=&quot;shortcut icon&quot; href=&quot;/favicon.ico&quot; type=&quot;image/x-icon&quot;&gt;
        ///
        ///	
        ///	
        ///	&lt;link href=&quot;https://store.akamai.steamstatic.com/public/shared/css/motiva_sans.css?v=Rc2hpzg2Ex3T&amp;amp;l=english&quot; rel=&quot;stylesheet&quot; type=&quot;t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Texture_Assembler {
            get {
                return ResourceManager.GetString("Texture-Assembler", resourceCulture);
            }
        }
    }
}
